name: Node.js CI and Deploy

on:
    push:
        branches: ['main']

jobs:
    build-and-deploy:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Verify VITE_API_URL secret
              run: |
                  if [ -z "${{ secrets.VITE_API_URL }}" ]; then
                      echo "Error: VITE_API_URL secret is not set." >&2
                      exit 1
                  fi

            - name: Create .env file
              run: |
                  echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env

            - name: Install dependencies
              run: npm i

            - name: Build project
              run: npm run build --if-present
              env:
                  VITE_API_URL: ${{ secrets.VITE_API_URL }}
